# Generated by Django 4.0.4 on 2022-07-24 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('car_year', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('bus_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TroubleCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('trouble_code_system', models.CharField(max_length=100)),
                ('condition_description', models.CharField(max_length=500)),
                ('alarm_on', models.BooleanField(default=False)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diagnostics.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(default='', max_length=100)),
                ('mark', models.CharField(default='', max_length=100)),
                ('engine_power', models.FloatField(default=0)),
                ('automatic', models.CharField(default='', max_length=100)),
                ('barometric_pressure', models.FloatField(default=0)),
                ('engine_coolant_temp', models.FloatField(default=0)),
                ('fuel_level', models.FloatField(default=0)),
                ('engine_load', models.FloatField(default=0)),
                ('ambient_air_temp', models.FloatField(default=0)),
                ('engine_rpm', models.FloatField(default=0)),
                ('intake_manifold_pressure', models.FloatField(default=0)),
                ('maf', models.FloatField(default=0)),
                ('long_term_fuel_trim_bank_2', models.CharField(default='', max_length=100)),
                ('fuel_type', models.CharField(default='', max_length=100)),
                ('air_intake_temp', models.FloatField(default=0)),
                ('fuel_pressure', models.FloatField(default=0)),
                ('speed', models.FloatField(default=0)),
                ('short_term_fuel_trim_bank_2', models.CharField(default='', max_length=100)),
                ('short_term_fuel_trim_bank_1', models.CharField(default='', max_length=100)),
                ('engine_runtime', models.CharField(default='', max_length=100)),
                ('throttle_pos', models.FloatField(default=0)),
                ('dtc_number', models.CharField(default='', max_length=100)),
                ('trouble_codes', models.CharField(default='', max_length=100)),
                ('timing_advance', models.FloatField(default=0)),
                ('equiv_ratio', models.FloatField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('hour', models.IntegerField(default=0)),
                ('days_of_week', models.IntegerField(default=0)),
                ('months', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostics.vehicle')),
            ],
        ),
    ]
