# Generated by Django 4.0.4 on 2022-08-04 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCenters',
            fields=[
                ('service_center_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='air_intake_temp',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='ambient_air_temp',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='automatic',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='barometric_pressure',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='days_of_week',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='dtc_number',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='engine_coolant_temp',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='engine_load',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='engine_power',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='engine_rpm',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='engine_runtime',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='equiv_ratio',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='fuel_level',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='fuel_pressure',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='intake_manifold_pressure',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='long_term_fuel_trim_bank_2',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='maf',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='months',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='short_term_fuel_trim_bank_1',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='short_term_fuel_trim_bank_2',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='throttle_pos',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='timing_advance',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='trouble_codes',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='year',
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='battery_charge',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='battery_current',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='battery_health',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='battery_temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='battery_voltage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='distance_covered',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='run_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='state',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='troublecode',
            name='clearance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='troublecode',
            name='notification_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_vehicle', to='diagnostics.vehicle'),
        ),
        migrations.AlterField(
            model_name='troublecode',
            name='alarm_on',
            field=models.CharField(default='ON', max_length=20),
        ),
        migrations.AlterField(
            model_name='troublecode',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trouble_code_vehicle', to='diagnostics.vehicle'),
        ),
        migrations.CreateModel(
            name='MaintenanceSchedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('service_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_service_center', to='diagnostics.servicecenters')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_vehicle', to='diagnostics.vehicle')),
            ],
        ),
    ]
