# Generated by Django 4.0.4 on 2022-08-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0002_servicecenters_remove_diagnostic_air_intake_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='battery_health',
            field=models.CharField(default='Good', max_length=50),
        ),
    ]
