# Generated by Django 4.0.4 on 2022-08-05 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0003_alter_diagnostic_battery_health'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fuel_level', models.FloatField(default=0)),
                ('engine_rpm', models.FloatField(default=0)),
                ('engine_coolant_temp', models.FloatField(default=0)),
                ('run_hours', models.FloatField(default=0)),
                ('distance_covered', models.FloatField(default=0)),
                ('speed', models.FloatField(default=0)),
                ('state', models.CharField(default='Active', max_length=20)),
                ('battery_voltage', models.FloatField(default=0)),
                ('throttle_position', models.FloatField(default=0)),
                ('maf_flow_rate', models.FloatField(default=0)),
                ('engine_load', models.FloatField(default=0)),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
                ('engine_power', models.FloatField(default=0)),
                ('barometric_pressure', models.FloatField(default=0)),
                ('air_intake_temp', models.FloatField(default=0)),
                ('fuel_type', models.CharField(default='Biodiesel_Ethanol', max_length=100)),
                ('engine_runtime', models.CharField(default='0', max_length=20)),
                ('timing_advance', models.FloatField(default=0)),
                ('equiv_ratio', models.FloatField(default=0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_vehicle', to='diagnostics.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='EvDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battery_charge', models.FloatField(default=0)),
                ('battery_health', models.CharField(default='Good', max_length=50)),
                ('battery_temperature', models.FloatField(default=0)),
                ('run_hours', models.FloatField(default=0)),
                ('distance_covered', models.FloatField(default=0)),
                ('speed', models.FloatField(default=0)),
                ('state', models.CharField(default='Active', max_length=20)),
                ('battery_voltage', models.FloatField(default=0)),
                ('battery_current', models.FloatField(default=0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ev_vehicle', to='diagnostics.vehicle')),
            ],
        ),
        migrations.DeleteModel(
            name='Diagnostic',
        ),
    ]
