# Generated by Django 4.0.4 on 2022-08-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0004_enginediagnostic_evdiagnostic_delete_diagnostic'),
    ]

    operations = [
        migrations.AddField(
            model_name='evdiagnostic',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='evdiagnostic',
            name='lng',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='evdiagnostic',
            name='motor_speed',
            field=models.FloatField(default=0),
        ),
    ]
