# Generated by Django 4.0.4 on 2022-08-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0005_evdiagnostic_lat_evdiagnostic_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedules',
            name='alarm',
            field=models.IntegerField(default=0),
        ),
    ]
