# Generated by Django 4.0.4 on 2022-07-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('incident_type', models.CharField(blank=True, default='', max_length=100)),
                ('incident_cause', models.CharField(blank=True, default='', max_length=200)),
                ('lat', models.FloatField(default=0)),
                ('long', models.FloatField(default=0)),
                ('road_condition', models.CharField(blank=True, default='', max_length=500)),
                ('incident_cost', models.IntegerField(default=0, null=True)),
                ('license_number', models.CharField(blank=True, default='', max_length=50)),
                ('temp', models.FloatField(blank=True, default=0)),
                ('pressure', models.FloatField(blank=True, default=0)),
                ('humidity', models.FloatField(blank=True, default=0)),
                ('visibility', models.FloatField(blank=True, default=0)),
                ('wind_speed', models.FloatField(blank=True, default=0)),
                ('clouds', models.FloatField(blank=True, default=0)),
                ('weather_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
